"""
ALAS Plan Executor — Sequential step executor with rollback support.

Executes plans generated by the planner, step by step:
- Runs each step using the tool registry
- Tracks progress and results
- Rolls back on failure (if rollback commands are defined)
- Supports human-in-the-loop checkpoints for ASK-tier steps
"""

import logging
from typing import Optional, Callable
from datetime import datetime

from backend.app.planning.planner import ExecutionPlan, PlanStep

logger = logging.getLogger("alas.planning.executor")

# Persistent plan storage
_plans: dict[str, ExecutionPlan] = {}


def store_plan(plan: ExecutionPlan) -> None:
    """Store a plan for later execution or reference."""
    _plans[plan.id] = plan


def get_plan(plan_id: str) -> Optional[ExecutionPlan]:
    """Retrieve a stored plan."""
    return _plans.get(plan_id)


def get_all_plans() -> list[dict]:
    """Get all stored plans."""
    return [p.to_dict() for p in sorted(
        _plans.values(),
        key=lambda p: p.created_at,
        reverse=True,
    )]


async def execute_plan(
    plan: ExecutionPlan,
    progress_callback: Optional[Callable] = None,
    skip_approval: bool = False,
) -> ExecutionPlan:
    """
    Execute a plan step by step.
    
    Args:
        plan: The execution plan to run.
        progress_callback: Optional callback(step_number, total, description, status)
                          for real-time progress updates.
        skip_approval: If True, skip approval checks (for trusted plans).
    
    Returns:
        The updated plan with results.
    """
    from backend.app.llm.legacy_tools import TOOL_FUNCTIONS

    plan.status = "executing"
    store_plan(plan)
    total_steps = len(plan.steps)

    logger.info(f"▶️ Executing plan: {plan.goal} ({total_steps} steps)")

    for i, step in enumerate(plan.steps):
        plan.current_step = i + 1

        # Check if step requires approval and we're not skipping
        if step.requires_approval and not skip_approval:
            step.status = "pending"
            step.result = "⏸️ This step requires user approval. Skipping for now."
            logger.info(f"   ⏸️ Step {step.step_number}: Requires approval, skipping")

            if progress_callback:
                await _call_progress(progress_callback, i + 1, total_steps, step.description, "skipped")
            continue

        step.status = "running"

        if progress_callback:
            await _call_progress(progress_callback, i + 1, total_steps, step.description, "running")

        logger.info(f"   ▶️ Step {step.step_number}/{total_steps}: {step.description}")

        try:
            result = _execute_step(step)
            step.status = "completed"
            step.result = result

            logger.info(f"   ✅ Step {step.step_number} completed")

            if progress_callback:
                await _call_progress(progress_callback, i + 1, total_steps, step.description, "completed")

        except Exception as e:
            step.status = "failed"
            step.error = str(e)
            logger.error(f"   ❌ Step {step.step_number} failed: {e}")

            if progress_callback:
                await _call_progress(progress_callback, i + 1, total_steps, step.description, "failed")

            # Attempt rollback of completed steps
            plan.status = "failed"
            await _rollback_plan(plan, up_to_step=i)
            store_plan(plan)
            return plan

    # All steps completed
    completed_count = sum(1 for s in plan.steps if s.status == "completed")
    if completed_count == total_steps:
        plan.status = "completed"
    else:
        plan.status = "completed"  # Partial completion (some skipped)

    plan.completed_at = datetime.now().isoformat()
    store_plan(plan)

    logger.info(f"✅ Plan completed: {plan.goal} ({completed_count}/{total_steps} steps)")
    return plan


def _execute_step(step: PlanStep) -> str:
    """Execute a single plan step using the tool registry."""
    from backend.app.llm.legacy_tools import TOOL_FUNCTIONS

    tool_name = step.tool
    args = step.args or {}

    # Map special tool names
    tool_map = {
        "run_code": "_run_code_tool",
        "git_operation": "_run_git_tool",
        "research_topic": "_run_research_tool",
    }

    if tool_name in tool_map:
        return globals()[tool_map[tool_name]](args)

    # Use the standard tool registry
    if tool_name in TOOL_FUNCTIONS:
        func = TOOL_FUNCTIONS[tool_name]
        return func(**args)
    else:
        raise ValueError(f"Unknown tool: {tool_name}")


def _run_code_tool(args: dict) -> str:
    """Execute code via sandbox."""
    from backend.app.sandbox.executor import run_code
    result = run_code(
        code=args.get("code", ""),
        language=args.get("language", "python"),
        working_dir=args.get("working_dir"),
    )
    return result.to_str()


def _run_git_tool(args: dict) -> str:
    """Execute git operation."""
    from backend.app.tools.git_agent import git_operation
    return git_operation(**args)


def _run_research_tool(args: dict) -> str:
    """Execute research."""
    from backend.app.tools.research_agent import research_topic
    return research_topic(**args)


async def _rollback_plan(plan: ExecutionPlan, up_to_step: int) -> None:
    """
    Roll back completed steps in reverse order.
    
    Args:
        plan: The plan to roll back.
        up_to_step: Roll back steps 0..up_to_step (exclusive).
    """
    import subprocess

    logger.info(f"🔄 Rolling back plan: {plan.goal} (steps 1-{up_to_step})")

    for i in range(up_to_step - 1, -1, -1):
        step = plan.steps[i]
        if step.status != "completed" or not step.rollback_cmd:
            continue

        logger.info(f"   🔄 Rolling back step {step.step_number}: {step.rollback_cmd}")

        try:
            result = subprocess.run(
                step.rollback_cmd,
                shell=True,
                capture_output=True,
                text=True,
                timeout=15,
            )
            if result.returncode == 0:
                step.status = "rolled_back"
                logger.info(f"   ✅ Rollback successful for step {step.step_number}")
            else:
                logger.warning(
                    f"   ⚠️ Rollback failed for step {step.step_number}: {result.stderr}"
                )
        except Exception as e:
            logger.error(f"   ❌ Rollback error for step {step.step_number}: {e}")

    plan.status = "rolled_back"


async def _call_progress(callback: Callable, step: int, total: int, desc: str, status: str):
    """Safely call a progress callback."""
    import asyncio
    try:
        if asyncio.iscoroutinefunction(callback):
            await callback(step, total, desc, status)
        else:
            callback(step, total, desc, status)
    except Exception as e:
        logger.error(f"Progress callback error: {e}")
